import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "./compoments/bootstrap/Bootstraptest";
import { AuthProider } from "./Providers/AuthProviders";
import { CarContextProvider } from "./Providers/CarProviders";
import Navbar from "./compoments/Navbar/Navbar";
import Footer from "./compoments/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

        <AuthProider>
          <CarContextProvider>


          <Navbar/>

        {children}

        <Footer/>
        <BootstrapClient/>
          </CarContextProvider>
        </AuthProider>
      </body>
    </html>
  );
}
